spring:
  application:
    name: appointmed

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_APPOINTMED_REALM} #http://keycloak:8080/realms/appointmed #http://localhost/realms/appointmed
  config:
    import: vault://

  cloud:
    vault:
      uri: ${VAULT_URL}
      token: ${VAULT_TOKEN}

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_APPOINTMED_CLIENTID}
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 9080
  error:
    include-message: always

custom-env:
  keycloak:
    url: ${KEYCLOAK_URL}
    appointmed-realm: ${KEYCLOAK_APPOINTMED_REALM}
    appointmed-clientId: ${KEYCLOAK_APPOINTMED_CLIENTID}

  mongodb:
    host: ${MONGODB_HOST}
    port: ${MONGODB_PORT}
    database: ${MONGODB_DATABASE}

  smtp:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}

  google:
    oauth2:
      clientId: ${GOOGLE_OAUTH2_CLIENTID}
